export const GET_FORMS_CONFIGURATION_ALL = 'GET_FORMS_CONFIGURATION_ALL';
export const GET_FORMS_CONFIGURATION = 'GET_FORMS_CONFIGURATION';

export const GET_FORMS_CATEGORIES_ALL = 'GET_FORMS_CATEGORIES_ALL';
